### ISSUE TITLE
Python2/python3 mismatches ?

### ISSUE THREAD

**Issue by SkippyleGrandGourou** [czpython/python-amazon-mws#42]
I just installed `python-amazon-mws` from `pip`.  I first tried python2.7 as usual :

    $ python
    Python 2.7.10 (default, Sep  8 2015, 17:20:17) 
    [GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from mws import mws
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.7/site-packages/mws/__init__.py", line 5, in <module>
        from .mws import *  # NOQA
      File "/usr/lib/python2.7/site-packages/mws/mws.py", line 23, in <module>
        from urllib.parse import quote as urllib_quote
    ImportError: No module named parse

Ok, `urllib.parse` is python3, right ?  So I installed `python-amazon-mws` for python3 (using `python3 -m pip install python-amazon-mws`), then :

    $ python3
    Python 3.4.3 (default, Jun 29 2015, 12:16:01) 
    [GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from mws import mws
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python3.4/site-packages/mws/mws.py", line 204
        except HTTPError, e:
                        ^
    SyntaxError: invalid syntax

Er, `except HTTPError, e` is python2, right ?

I'm quite puzzled…  Looking at  `/usr/lib/python2.7/site-packages/mws/mws.py` and `/usr/lib/python3.4/site-packages/mws/mws.py`, it seems indeed there is a python2/python3 mismatch.

**Comment by SkippyleGrandGourou** [comment]
Indeed after switching `/usr/lib/python2.7/site-packages/mws/` and `/usr/lib/python3.4/site-packages/mws/` (and copying `/usr/lib/python2.7/site-packages/amazon_mws-0.2.3-py2.7.egg-info` into `/usr/lib/python3.4/site-packages/amazon_mws-0.2.3-py3.4.egg-info`), it seems to work (at least `from mws import mws`).

**Comment by GriceTurrble** [comment]
The version on PyPi is *way* out of date. The code in this repo is built mainly for 2.7, so it should work for you.

For Py3, I've forked this project for my own needs and had to make edits for the issues you mentioned to get it working.

**Comment by wesleybowman** [comment]
This seems to still not work.

**Comment by jameshiew** [comment]
I have a 2/3 compatible fork at https://github.com/jameshiew/mws that is also on PyPI (`pip install mws`). Not super well tested but some helpful PRs have fixed the biggest bugs by this point.
